name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 Features
    when:
      labels: [feature, enhancement]
  - title: 🐛 Fixes
    when:
      labels: [bug]
  - title: 🧰 Maintenance
    when:
      labels: [chore, refactor, docs]
change-template: '- $TITLE (#$NUMBER) — @$AUTHOR'
template: |
  ## Changes
  $CHANGES
