# Copyright 2025-2026 STARGA Inc.
# Licensed under the Apache License, Version 2.0 (the "License").
# Part of the MIND project (Machine Intelligence Native Design).

"""Intermediate representation used by the PyTorch / JAX → MIND bridge."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Iterable, List, Sequence, Tuple


class OpKind(Enum):
    """Subset of operations the bridge currently lowers natively.

    Anything not in this enum routes through ``UnsatContext`` so the
    AI-assisted proof step can see it.
    """

    MATMUL = "matmul"
    CONV2D = "conv2d"
    ADD = "add"
    SUB = "sub"
    MUL = "mul"
    DIV = "div"
    RELU = "relu"
    SOFTMAX = "softmax"
    LAYERNORM = "layernorm"
    RESHAPE = "reshape"
    TRANSPOSE = "transpose"
    REDUCE_SUM = "reduce_sum"
    REDUCE_MEAN = "reduce_mean"


@dataclass(frozen=True)
class MindOp:
    """One op in the lowered graph."""

    name: str
    kind: OpKind
    inputs: Tuple[str, ...]
    output: str
    shape: Tuple[int, ...]
    dtype: str = "f32"

    def to_mind(self) -> str:
        ins = ", ".join(self.inputs)
        shape = "x".join(str(s) for s in self.shape) if self.shape else "scalar"
        return (
            f"  let {self.output}: tensor<{shape}x{self.dtype}> = "
            f"{self.kind.value}({ins})  // {self.name}"
        )


@dataclass
class MindModule:
    """The full lowered module.

    Use :meth:`emit` to render the canonical ``.mind`` text.
    """

    name: str
    inputs: List[Tuple[str, Tuple[int, ...], str]] = field(default_factory=list)
    ops: List[MindOp] = field(default_factory=list)
    output: str = ""

    def add_input(self, name: str, shape: Sequence[int], dtype: str = "f32") -> None:
        self.inputs.append((name, tuple(shape), dtype))

    def add_op(self, op: MindOp) -> None:
        self.ops.append(op)

    def set_output(self, name: str) -> None:
        self.output = name

    def emit(self) -> str:
        """Render to canonical MIND source text.

        The output is intentionally simple and stable; it is intended to
        pass through ``mindc --check`` without any post-processing.
        """
        lines = [f"// Auto-generated by tools/pytorch_bridge for `{self.name}`"]
        if self.inputs:
            args = ", ".join(
                f"{n}: tensor<{'x'.join(str(s) for s in shape)}x{dtype}>"
                for (n, shape, dtype) in self.inputs
            )
        else:
            args = ""
        lines.append(f"fn {self.name}({args}) {{")
        for op in self.ops:
            lines.append(op.to_mind())
        if self.output:
            lines.append(f"  return {self.output}")
        lines.append("}")
        return "\n".join(lines) + "\n"


def kind_from_str(name: str) -> OpKind | None:
    """Lookup helper used by the PyTorch / JAX adapters."""
    canonical = name.lower()
    aliases = {
        "matmul": OpKind.MATMUL,
        "mm": OpKind.MATMUL,
        "linear": OpKind.MATMUL,
        "gemm": OpKind.MATMUL,
        "conv": OpKind.CONV2D,
        "conv2d": OpKind.CONV2D,
        "add": OpKind.ADD,
        "sub": OpKind.SUB,
        "mul": OpKind.MUL,
        "div": OpKind.DIV,
        "relu": OpKind.RELU,
        "softmax": OpKind.SOFTMAX,
        "layernorm": OpKind.LAYERNORM,
        "reshape": OpKind.RESHAPE,
        "transpose": OpKind.TRANSPOSE,
        "reduce_sum": OpKind.REDUCE_SUM,
        "sum": OpKind.REDUCE_SUM,
        "reduce_mean": OpKind.REDUCE_MEAN,
        "mean": OpKind.REDUCE_MEAN,
    }
    return aliases.get(canonical)


def supported_kinds() -> Iterable[OpKind]:
    return list(OpKind)
