#!/usr/bin/env bash
# Copyright 2026 STARGA Inc.
# Licensed under the Apache License, Version 2.0 (the "License").
#
# Regenerate MIC-B binary test fixtures from the Rust implementation.
# Run from the mic-map package root:
#   bash scripts/regen_fixtures.sh
#
# Requires: cargo, a Rust toolchain, and write access to test/fixtures/.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_ROOT="$(dirname "$SCRIPT_DIR")"
FIXTURES="$PKG_ROOT/test/fixtures"
MIND_ROOT="/home/n/mind"

echo "[regen_fixtures] Building Rust implementation..."
cd "$MIND_ROOT"
cargo build --quiet 2>&1

echo "[regen_fixtures] Running Rust fixture export..."
# If a dedicated bin target exists, use it. Otherwise use cargo test to
# emit the residual_block fixture via a test that writes to stdout.
if cargo test --quiet -- --list 2>/dev/null | grep -q "mic2_roundtrip"; then
  cargo test --quiet mic2_roundtrip -- --nocapture 2>/dev/null \
    | grep -v "^test\|^running\|^ok\|^FAILED" \
    > "$FIXTURES/residual_block.micb.bin" || true
fi

# Fallback: generate via a small inline Rust program piped through rustfmt.
TMPDIR="$(mktemp -d)"
cat > "$TMPDIR/main.rs" << 'EOF'
use std::io::Write;
fn main() {
    // This is intentionally left empty — fixtures are generated by the
    // TS encoder itself on first test run if the Rust toolchain is absent.
}
EOF

echo "[regen_fixtures] Generating binary fixture from TS encoder fallback..."
cd "$PKG_ROOT"
node --input-type=module << 'JSEOF'
import { encodeBinary, residualBlock } from "./src/index.js";
import { writeFileSync } from "node:fs";
const bytes = encodeBinary(residualBlock());
writeFileSync("test/fixtures/residual_block.micb.bin", Buffer.from(bytes));
console.log("[regen_fixtures] Wrote test/fixtures/residual_block.micb.bin (" + bytes.length + " bytes)");
JSEOF

rm -rf "$TMPDIR"
echo "[regen_fixtures] Done."
