// Copyright 2025 STARGA Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! HTML page scaffolding for `mindc doc` output.
//!
//! All CSS is embedded inline — zero external resources, pages work offline.

/// Embedded stylesheet (~3 KB).
const CSS: &str = r#"
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
     background:#0f1117;color:#c9d1d9;line-height:1.6;padding:1.5rem 2rem}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
h1.module-title{font-size:1.6rem;font-weight:700;margin-bottom:1.2rem;
                color:#e6edf3;border-bottom:1px solid #30363d;padding-bottom:.5rem}
h2.mod-section{font-size:1.1rem;font-weight:600;margin:1.4rem 0 .4rem;color:#e6edf3}
table.module-index{width:100%;border-collapse:collapse;margin-bottom:1.5rem}
table.module-index th{text-align:left;padding:.4rem .8rem;
                       border-bottom:2px solid #30363d;color:#8b949e;font-weight:600}
table.module-index td{padding:.35rem .8rem;border-bottom:1px solid #21262d}
table.module-index tr:hover td{background:#161b22}
ul.item-list{list-style:none;padding-left:.5rem;margin-bottom:.8rem}
ul.item-list li{padding:.15rem 0}
.item{background:#161b22;border:1px solid #30363d;border-radius:6px;
      padding:1rem 1.2rem;margin-bottom:1rem}
h3.signature{font-size:1rem;font-family:"SFMono-Regular",Consolas,"Liberation Mono",
             Menlo,monospace;font-weight:600;margin-bottom:.6rem;
             background:#0d1117;border-radius:4px;padding:.4rem .6rem}
.kind{color:#ff7b72;font-weight:700;margin-right:.3rem}
.name{color:#d2a8ff}
.params{color:#c9d1d9}
.docs{font-size:.95rem;color:#c9d1d9;margin-top:.5rem;line-height:1.7}
.docs p{margin-bottom:.5rem}
.docs code,.docs pre{font-family:"SFMono-Regular",Consolas,monospace;
                      background:#0d1117;border-radius:3px}
.docs code{padding:.1rem .3rem;font-size:.88rem;color:#79c0ff}
.docs pre{padding:.7rem 1rem;overflow-x:auto;border:1px solid #30363d;
          margin:.5rem 0;font-size:.88rem}
.docs pre code{padding:0;background:none}
.docs strong{color:#e6edf3;font-weight:600}
.docs em{font-style:italic;color:#a5d6ff}
p.empty{color:#8b949e;font-style:italic}
nav.breadcrumb{font-size:.85rem;margin-bottom:1rem;color:#8b949e}
nav.breadcrumb a{color:#58a6ff}
footer{margin-top:2rem;font-size:.8rem;color:#484f58;border-top:1px solid #21262d;
       padding-top:.8rem}
"#;

/// Produce a complete HTML page.
///
/// - `title` is used in `<title>` and the breadcrumb.
/// - `body` is the raw HTML content (already escaped where needed).
/// - `root_prefix` is the relative path back to the doc root (e.g. `"../../"`).
pub fn page(title: &str, body: &str, root_prefix: &str) -> String {
    let breadcrumb = if !root_prefix.is_empty() {
        format!(
            "<nav class=\"breadcrumb\"><a href=\"{root_prefix}index.html\">Index</a> / {title}</nav>\n"
        )
    } else {
        String::new()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} — MIND docs</title>
<style>{CSS}</style>
</head>
<body>
{breadcrumb}{body}
<footer>Generated by <code>mindc doc</code></footer>
</body>
</html>
"#
    )
}
